--- # This playbook is to install tomcat using variables 
- hosts: localhost
  gather_facts: no
  become: yes
  become_user: svctmcat
  become_method: sudo 
  vars_files: 
  - tomcat_vars.yml
  tasks:
  - name: Check filesystem facts
    include: fact_check.yml
  - name: Install package
    include: installation.yml
  - name: Run post install steps
    include: post_install.yml 
