--- #This playbook uses jinja2 for server.xml 
- hosts: localhost
  gather_facts: no
  vars_files:
    - /home/xgzpqkon/playbooks/tomcat/tomcat_vars.yml
  become: yes
  become_user: '{{ svc_user }}'
  become_method: su
  tasks:
#  - name: port number
#    include: ports.yml
#    with_sequence: start=0 end={{ instances|int - 1 }}
  - name: using logging.properties template
    template: 
      src: logging.properties.j2
      dest: "/app/tomcat/server{{ item }}/conf/logging.properties"
      owner: svctmcat
      group: domain_users
      mode: '0755'
    with_sequence: start=1 end={{ instances }}

